(function () {
    'use strict';

    angular
        .module('Chefonia')
        .factory('MappingService', MappingService);
    function MappingService() {
        var service = {};
        service.getAllOptions = getAllOptions;
        service.getCategory = getCategory;

        var mapping = {
            "Chocolate Cake": "BAKERY",
            "Black Forest Cake": "BAKERY",
            "Strawberry Cake": "BAKERY",
            "Fresh Cream Cake": "BAKERY",
            "Pure Veg Cakes": "BAKERY",
            "Two Tier Cake": "BAKERY",

            "Mango Achar": "PICKLES",
            "Mango Pickle": "PICKLES",
            "Achar": "PICKLES",
            "Avala": "PICKLES",
            "Black Lemon Achar": "PICKLES",
            "Lemon Pickle": "PICKLES",
            "Sprouted Methi Seeds Achar": "PICKLES",
            "Karela Aachar": "PICKLES",
            "Red Chilly Achar": "PICKLES",
            "Green Chilly Aachar": "PICKLES",
            "Mahani Aachar": "PICKLES",
            "Dryfruit Achar": "PICKLES",
            "Woodapple Preserve Achar": "PICKLES",

            "Chocolate": "CHOCOLATES",
            "Dark Chocolates": "CHOCOLATES",
            "Almonds Dark Chocolates": "CHOCOLATES",
            "Milk Chocolates": "CHOCOLATES",
            "Almonds Milk Chocolates": "CHOCOLATES",
            "Dark Chocolates Balls": "CHOCOLATES",
            "Cashew Chocolate": "CHOCOLATES",
            "Rasin Chocolate": "CHOCOLATES",
            "Walnut Chocolate": "CHOCOLATES",
            "White Almond Roasted Chocolate": "CHOCOLATES",
            "White Cashew Roasted Chocolate": "CHOCOLATES",
            "Chocolates": "CHOCOLATES",
            "White Chocolate with Choco Chips": "CHOCOLATES",
            "White Chocolate with Strawberry": "CHOCOLATES",
            "White Chocolate with Pineapple": "CHOCOLATES",
            "Dark Butter Scotch Chocolate": "CHOCOLATES",
            "White Butter Scotch Chocolate": "CHOCOLATES",
            "White Fruit & Nuts Chocolate": "CHOCOLATES",
            "Dark Chocolate Caramel": "CHOCOLATES",
            "Badam Chocolates Assorted": "CHOCOLATES",
            "Fruit & Nuts Chocolates": "CHOCOLATES",
            "Butterscotch Chocolates": "CHOCOLATES",
            "Crackle Chocolates": "CHOCOLATES",
            "Almond Rock Chocolates": "CHOCOLATES",
            "Pan masala Chocolates": "CHOCOLATES",
            "Orange Chocolates": "CHOCOLATES",
            "Pineapple Chocolates": "CHOCOLATES",
            "Florentine Chocolates": "CHOCOLATES",
            "Caramel Chocolates": "CHOCOLATES",
            "coffee Chocolates": "CHOCOLATES",
            "Hazelnut Chocolates": "CHOCOLATES",
            "Oreo Chocolates": "CHOCOLATES",

            "Handwa": "DISHES",
            "Undhia": "DISHES",

            "Paan Mukhwas": "MOUTH_FRESHNERS",
            "Mouth Freshner": "MOUTH_FRESHNERS",
            "Freshner": "MOUTH_FRESHNERS",

            "Chocolate Brownie": "BROWNIE",
            "Walnuts Brownie": "BROWNIE",
            "Nuts Brownie": "BROWNIE",
            "Mocha coconut Brownie": "BROWNIE",
            "Spiced Brownie": "BROWNIE",
            "Almond Caramel Brownie": "BROWNIE",
            "Chico Chip Brownie": "BROWNIE",
            "Dates Brownie": "BROWNIE",

            "Churmura Chivda": "MIXTURES",
            "Chivda": "MIXTURES",
            "Poha Chivda": "MIXTURES",
            "Murmura Chivda": "MIXTURES",
            "Chakli": "MIXTURES",
            "Metkut": "MIXTURES",
            "Shankarpali": "SWEETS",
            "Shev": "MIXTURES",
            "Mix Chivda": "MIXTURES",
            "Glouse Para Namkeen": "MIXTURES",
            "Dry Bhel Namkeen": "MIXTURES",
            "Bhel Puri Namkeen": "MIXTURES",
            "Chana Dal Namkeen": "MIXTURES",
            "Lasan Sev Namkeen": "MIXTURES",
            "Jadi Sev Namkeen": "MIXTURES",
            "Tam Tam Namkeen": "MIXTURES",
            "Khatta Mitha Namkeen": "MIXTURES",
            "Tika Chavana Namkeen": "MIXTURES",
            "Bhel Sev Namkeen": "MIXTURES",
            "Nylon Sev Namkeen": "MIXTURES",
            "SP. Nylon Sev Namkeen": "MIXTURES",
            "Bhavangari Namkeen": "MIXTURES",
            "SP. Bhavangari Namkeen": "MIXTURES",
            "Dahi Mamari Masala Namkeen": "MIXTURES",
            "Dahi Mamari Moli Namkeen": "MIXTURES",
            "Dal Munth Namkeen": "MIXTURES",
            "Phudina Dhaniya Dal Namkeen": "MIXTURES",
            "Masala Sing Namkeen": "MIXTURES",
            "SP. Bhakjarvadi Namkeen": "MIXTURES",
            "SP.Dry Kachori Namkeen": "MIXTURES",
            "Singh Bhujiya Namkeen": "MIXTURES",
            "Ratlami Sev Namkeen": "MIXTURES",
            "Chana Jor Tikha Namkeen": "MIXTURES",
            "Chana Jor Mola Namkeen": "MIXTURES",
            "Mung Dal Namkeen": "MIXTURES",
            "Bikaneri Sev Namkeen": "MIXTURES",
            "Masala Chana Namkeen": "MIXTURES",
            "Alu Sev Namkeen": "MIXTURES",
            "Alu Palak Bhujiya SEV Namkeen": "MIXTURES",
            "Tometo Sev Namkeen": "MIXTURES",
            "Chinese Sev Namkeen": "MIXTURES",
            "SP. Kela Waffers Mari Namkeen": "MIXTURES",
            "SP. Farali Chevda Tikha Namkeen": "MIXTURES",
            "SP.FARALI CHEVDA MOLA Namkeen": "MIXTURES",
            "SP.KELA WAFFERS TIKHI Namkeen": "MIXTURES",
            "Mini Papad Namkeen": "MIXTURES",
            "Cheezee Ball Namkeen": "MIXTURES",
            "Methi Para Namkeen": "MIXTURES",
            "Methi Puri Namkeen": "MIXTURES",
            "Bhadaran Mung Namkeen": "MIXTURES",
            "Chat Pata Mung Namkeen": "MIXTURES",
            "Soya Stick Namkeen": "MIXTURES",
            "Soya Chips Namkeen": "MIXTURES",
            "Rajwadi Khatta Mittha Namkeen": "MIXTURES",
            "Rajwadi Tikha Mittha Namkeen": "MIXTURES",
            "Phudina Ring Namkeen": "MIXTURES",
            "Tometo Ring Namkeen": "MIXTURES",
            "Manchurian Ring Namkeen": "MIXTURES",
            "Kela Mari Lambi Namkeen": "MIXTURES",
            "Kela Tikhi Lambi Namkeen": "MIXTURES",
            "Samosa Puri Namkeen": "MIXTURES",
            "Aalu Wafers Salty Namkeen": "MIXTURES",
            "Aalu Wafers Tikhi Namkeen": "MIXTURES",
            "Sev Mamaram Namkeen": "MIXTURES",
            "Paalak Ganthiya Namkeen": "MIXTURES",
            "Methi Ganthiya Namkeen": "MIXTURES",
            "Kela Chevda Mari Namkeen": "MIXTURES",
            "Kela Chevda Tikha Namkeen": "MIXTURES",
            "Paalak Ratlami Sev Namkeen": "MIXTURES",
            "Phudina Mogar Namkeen": "MIXTURES",
            "CHEEZE Mogar Namkeen": "MIXTURES",
            "Jira Raita Mamari Namkeen": "MIXTURES",
            "Kothmir Ganthia Namkeen": "MIXTURES",


            "Rava Ladu": "SWEETS",
            "Ladu": "SWEETS",
            "Besan Ladu": "SWEETS",
            "Gajar Halwa": "SWEETS",
            "Potato Barfi": "SWEETS",
            "Tomato Barfi": "SWEETS",
            "Nut Chikki": "SWEETS",
            "Til Chikki": "SWEETS",
            "Til Laddu": "SWEETS",
            "Coconut Barfi Delight": "SWEETS",
            "Besan Laddu": "SWEETS",
            "Khajur Anjir Roll": "SWEETS",

            "Shengdana Chutney": "CHUTNEY",
            "Jawas Chutney": "CHUTNEY",
            "Til Chutney": "CHUTNEY",
            "Karale Chutney": "CHUTNEY",


            "Nagli Papad": "PAPAD",
            "Udit Papad": "PAPAD",
            "Rice Papad": "PAPAD",
            "Potato Chips": "PAPAD",
            "Kurdai": "PAPAD",
            "Chips": "PAPAD",

            "White Dhokla": "SNACKS",
            "Thepla": "SNACKS",
            "Masala Khaakhara": "SNACKS",
            "Methi Khaakhara": "SNACKS",
            "Jira Khaakhara": "SNACKS",
            "Sada Khaakhara": "SNACKS",
            "Kothami Marcha Khaakhara": "SNACKS",
            "Chaat MASALA Khaakhara": "SNACKS",
            "Panipuri Khaakhara": "SNACKS",
            "Bhajipauv Khaakhara": "SNACKS",
            "Khatha Mitha Khaakhara": "SNACKS",
            "Masala Khakhra": "SNACKS",
            "Methi Khakhra": "SNACKS",
            "Jeera Khakhra": "SNACKS",
            "Plain Khakhra": "SNACKS",
            "Kothmir Chilli Khakhra": "SNACKS",
            "Ginger Chilli Khakhra": "SNACKS",
            "Chilli Garlic Khakhra": "SNACKS",
            "Chat Chaska Khakhra": "SNACKS",
            "Sp. Farali Khakhra": "SNACKS"
        };
        var keys = [
            "Chocolate Cake",
            "Cashew Chocolate",
            "Mango Pickle",
            "Til Chikki",
            "Almonds Milk Chocolates",
            "Chocolate Brownie",
            "Black Forest Cake",
            "Nuts Brownie",
            "Strawberry Cake",
            "Fresh Cream Cake",
            "Pure Veg Cakes",
            "Two Tier Cake",
            "Mango Achar",
            "Achar",
            "Black Lemon Achar",
            "Lemon Pickle",
            "Sprouted Methi Seeds Achar",
            "Karela Aachar",
            "Red Chilly Achar",
            "Green Chilly Aachar",
            "Mahani Aachar",
            "Dryfruit Achar",
            "Woodapple Preserve Achar",
            "Dark Chocolates",
            "Almonds Dark Chocolates",
            "Milk Chocolates",
            "Almonds Milk Chocolates",
            "Dark Chocolates Balls",
            "Cashew Chocolate",
            "Rasin Chocolate",
            "Walnut Chocolate",
            "White Almond Roasted Chocolate",
            "White Cashew Roasted Chocolate",
            "Chocolates",
            "White Chocolate with Choco Chips",
            "White Chocolate with Strawberry",
            "White Chocolate with Pineapple",
            "Dark Butter Scotch Chocolate",
            "White Butter Scotch Chocolate",
            "White Fruit & Nuts Chocolate",
            "Dark Chocolate Caramel",
            "Badam Chocolates Assorted",
            "Fruit & Nuts Chocolates",
            "Butterscotch Chocolates",
            "Crackle Chocolates",
            "Almond Rock Chocolates",
            "Pan masala Chocolates",
            "Orange Chocolates",
            "Pineapple Chocolates",
            "Florentine Chocolates",
            "Caramel Chocolates",
            "coffee Chocolates",
            "Hazelnut Chocolates",
            "Oreo Chocolates",
            "Handwa",
            "Undhia",
            "Paan Mukhwas",
            "Mouth Freshner",
            "Walnuts Brownie",
            "Mocha coconut Brownie",
            "Spiced Brownie",
            "Almond Caramel Brownie",
            "Chico Chip Brownie",
            "Dates Brownie",
            "Churmura Chivda",
            "Poha Chivda",
            "Murmura Chivda",
            "Chakli",
            "Metkut",
            "Shankarpali",
            "Shev",
            "Mix Chivda",
            "Glouse Para Namkeen",
            "Dry Bhel Namkeen",
            "Bhel Puri Namkeen",
            "Chana Dal Namkeen",
            "Lasan Sev Namkeen",
            "Jadi Sev Namkeen",
            "Tam Tam Namkeen",
            "Khatta Mitha Namkeen",
            "Tika Chavana Namkeen",
            "Bhel Sev Namkeen",
            "Nylon Sev Namkeen",
            "SP. Nylon Sev Namkeen",
            "Bhavangari Namkeen",
            "SP. Bhavangari Namkeen",
            "Dahi Mamari Masala Namkeen",
            "Dahi Mamari Moli Namkeen",
            "Dal Munth Namkeen",
            "Phudina Dhaniya Dal Namkeen",
            "Masala Sing Namkeen",
            "SP. Bhakjarvadi Namkeen",
            "SP.Dry Kachori Namkeen",
            "Singh Bhujiya Namkeen",
            "Ratlami Sev Namkeen",
            "Chana Jor Tikha Namkeen",
            "Chana Jor Mola Namkeen",
            "Mung Dal Namkeen",
            "Bikaneri Sev Namkeen",
            "Masala Chana Namkeen",
            "Alu Sev Namkeen",
            "Alu Palak Bhujiya SEV Namkeen",
            "Tometo Sev Namkeen",
            "Chinese Sev Namkeen",
            "SP. Kela Waffers Mari Namkeen",
            "SP. Farali Chevda Tikha Namkeen",
            "SP.FARALI CHEVDA MOLA Namkeen",
            "SP.KELA WAFFERS TIKHI Namkeen",
            "Mini Papad Namkeen",
            "Cheezee Ball Namkeen",
            "Methi Para Namkeen",
            "Methi Puri Namkeen",
            "Bhadaran Mung Namkeen",
            "Chat Pata Mung Namkeen",
            "Soya Stick Namkeen",
            "Soya Chips Namkeen",
            "Rajwadi Khatta Mittha Namkeen",
            "Rajwadi Tikha Mittha Namkeen",
            "Phudina Ring Namkeen",
            "Tometo Ring Namkeen",
            "Manchurian Ring Namkeen",
            "Kela Mari Lambi Namkeen",
            "Kela Tikhi Lambi Namkeen",
            "Samosa Puri Namkeen",
            "Aalu Wafers Salty Namkeen",
            "Aalu Wafers Tikhi Namkeen",
            "Sev Mamaram Namkeen",
            "Paalak Ganthiya Namkeen",
            "Methi Ganthiya Namkeen",
            "Kela Chevda Mari Namkeen",
            "Kela Chevda Tikha Namkeen",
            "Paalak Ratlami Sev Namkeen",
            "Phudina Mogar Namkeen",
            "CHEEZE Mogar Namkeen",
            "Jira Raita Mamari Namkeen",
            "Kothmir Ganthia Namkeen",
            "Rava Ladu",
            "Ladu",
            "Besan Ladu",
            "Gajar Halwa",
            "Potato Barfi",
            "Tomato Barfi",
            "Nut Chikki",
            "Til Laddu",
            "Coconut Barfi Delight",
            "Besan Laddu",
            "Khajur Anjir Roll",
            "Shengdana Chutney",
            "Jawas Chutney",
            "Til Chutney",
            "Karale Chutney",
            "Nagli Papad",
            "Udit Papad",
            "Rice Papad",
            "Potato Chips",
            "Kurdai",
            "Chips",
            "White Dhokla",
            "Thepla",
            "Masala Khaakhara",
            "Methi Khaakhara",
            "Jira Khaakhara",
            "Sada Khaakhara",
            "Kothami Marcha Khaakhara",
            "Chaat MASALA Khaakhara",
            "Panipuri Khaakhara",
            "Bhajipauv Khaakhara",
            "Khatha Mitha Khaakhara",
            "Masala Khakhra",
            "Methi Khakhra",
            "Jeera Khakhra",
            "Plain Khakhra",
            "Kothmir Chilli Khakhra",
            "Ginger Chilli Khakhra",
            "Chilli Garlic Khakhra",
            "Chat Chaska Khakhra",
            "Sp. Farali Khakhra"
        ];

        return service;

        function getAllOptions() {
            return keys;
        }

        function getCategory(key) {
            return mapping[key];
        }
    }
})();
